[package]
name = "disk-viz"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.14"
rayon = "1.10.0"
walkdir = "2.5.0"
eframe = "0.31.1"
rfd = "0.15.3"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
open = "5.3.2"
